// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioManager.Infrastructure.Persistence.Commom;

#nullable disable

namespace PortfolioManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240424004916_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioManager.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("due_at");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("ManagerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manager_email");

                    b.Property<decimal>("MinimumInvestmentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("minimum_investment_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ba38709-9633-4a93-9824-d4ee22951c26"),
                            CreatedAt = new DateTime(2024, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "XP Debêntures Incentivadas Hedge CP FIC FIM LP",
                            DueAt = new DateTime(2029, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            ManagerEmail = "manager@mail.com",
                            MinimumInvestmentAmount = 1000m,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("6610e835-8a46-45dd-8b3d-2e3a64eaec6a"),
                            CreatedAt = new DateTime(2024, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "XP BNP Multi Asset A.I. - Alta Alavancada",
                            DueAt = new DateTime(2029, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            ManagerEmail = "manager@mail.com",
                            MinimumInvestmentAmount = 5000m,
                            Version = 0u
                        });
                });

            modelBuilder.Entity("PortfolioManager.Domain.Users.PortfolioProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_product");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_portfolio_product_product_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_portfolio_product_user_id");

                    b.ToTable("portfolio_product", (string)null);
                });

            modelBuilder.Entity("PortfolioManager.Domain.Users.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_transaction");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_transaction_product_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_transaction_user_id");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("PortfolioManager.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aacbda5a-2add-469e-85b9-d14dff2eb38b"),
                            CreatedAt = new DateTime(2024, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            FirstName = "John",
                            IsAdmin = true,
                            Lastname = "Doe",
                            PasswordHash = "$2a$11$DsHUOKHXnObgR5.HCla.oegHc5SlhyeIkryF5gF.xFhWlTsWKnko6",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("0d706086-6829-45bc-ad95-b8b0d942aa84"),
                            CreatedAt = new DateTime(2024, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            IsAdmin = false,
                            Lastname = "Smith",
                            PasswordHash = "$2a$11$K4Pyu70lbon4I4bL25lFRuQRQHhjmbU3sb5kKrBr1sPLIbjmKSo66",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("8d4e4aa3-0bdf-44d3-ba6a-e3383eacebc7"),
                            CreatedAt = new DateTime(2024, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            IsAdmin = true,
                            Lastname = "Johnson",
                            PasswordHash = "$2a$11$pZPzG980V7GoM2UNos3l9.onTf3trhSkwWT8gUshmcZfInY36NV8.",
                            Version = 0u
                        });
                });

            modelBuilder.Entity("PortfolioManager.Domain.Users.PortfolioProduct", b =>
                {
                    b.HasOne("PortfolioManager.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_product_product_product_id");

                    b.HasOne("PortfolioManager.Domain.Users.User", "User")
                        .WithMany("PortfolioProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_product_users_user_id");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortfolioManager.Domain.Users.Transaction", b =>
                {
                    b.HasOne("PortfolioManager.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_product_product_id");

                    b.HasOne("PortfolioManager.Domain.Users.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_users_user_id");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortfolioManager.Domain.Users.User", b =>
                {
                    b.Navigation("PortfolioProducts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
