version: '3.8'

services:
  webapi:
    image: portfolio-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    networks:
      - app-network
    env_file: 
      - .env
  cache:
    image: redis:latest
    restart: always
    ports: 
      - '6379:6379'
    networks:
      - app-network      
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5      
    env_file: 
      - .env

volumes:
  postgres_data:

networks:
  app-network:
    name: app-network
