version: '3.8'

services:
  webapi:
    image: portfolio-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy      
    networks:
      - app-network
    env_file: 
      - .env
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5 
    env_file: 
      - .env
  redis:
    image: redis:latest
    restart: always
    ports: 
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5      
    networks:
      - app-network
volumes:
  postgres-data:

networks:
  app-network:
    name: app-network