// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioManager.Infrastructure.Persistence.Commom;

#nullable disable

namespace PortfolioManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240415235038_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioManager.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<ZonedDateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("02eb13a8-4d27-4eb4-89f6-7b7ee31c981c"),
                            CreatedAt = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(17132250372819489L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            IsAdmin = true,
                            PasswordHash = "$2a$11$mss.4ov4tduZDhiOPAIs8OXWNSqxndvePKDlp6C3q4RbgxQw4U.tu",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("29e7df09-7f8d-468f-9184-630d18f0bc6d"),
                            CreatedAt = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(17132250375130368L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            IsAdmin = false,
                            PasswordHash = "$2a$11$O0hM54kXoX3soYPh2neUUezHdjAWrdj1jFx8eFOSeKcLbo0BGFub6",
                            Username = "user1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
